<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <OutputType>WinExe</OutputType>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ApplicationManifest>app.manifest</ApplicationManifest>
        <AvaloniaUseCompiledBindingsByDefault>false</AvaloniaUseCompiledBindingsByDefault>
        <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
        <AppendRuntimeIdentifierToOutputPath>false</AppendRuntimeIdentifierToOutputPath>
        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
        <Configurations>Debug;Release</Configurations>
        <Platforms>AnyCPU;x64</Platforms>
    </PropertyGroup>
    <PropertyGroup Condition=" '$(Configuration)' == 'Debug' ">
      <OutputPath>../../../Binaries/VirtualSteward MkV/Debug/</OutputPath>
      <PlatformTarget>x64</PlatformTarget>
      <DebugType>pdbonly</DebugType>
    </PropertyGroup>
    <PropertyGroup Condition=" '$(Configuration)' == 'Release' ">
      <PlatformTarget>x64</PlatformTarget>
      <DebugType>none</DebugType>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Avalonia" Version="11.3.11"/>
        <PackageReference Include="Avalonia.Desktop" Version="11.3.11"/>
        <PackageReference Include="Avalonia.Themes.Fluent" Version="11.3.11"/>
        <PackageReference Include="Avalonia.Fonts.Inter" Version="11.3.11"/>
        <!--Condition below is needed to remove Avalonia.Diagnostics package from build output in Release configuration.-->
        <PackageReference Include="Avalonia.Diagnostics" Version="11.3.11">
            <IncludeAssets Condition="'$(Configuration)' != 'Debug'">None</IncludeAssets>
            <PrivateAssets Condition="'$(Configuration)' != 'Debug'">All</PrivateAssets>
        </PackageReference>
        <PackageReference Include="Xaml.Behaviors.Avalonia" Version="11.3.9.5" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\ACLibrary\ACLibrary.csproj" />
      <ProjectReference Include="..\Framework\Framework.csproj" />
    </ItemGroup>

    <ItemGroup>
      <Folder Include="Features\ResetReplay\" />
      <Folder Include="Pages\" />
    </ItemGroup>

    <ItemGroup>
      <AdditionalFiles Include="Pages\Main\Pages\Main.axaml" />
      <AdditionalFiles Include="Pages\Replays\Pages\Replays.axaml" />
    </ItemGroup>

    <ItemGroup>
      <None Remove="Assets\favicon.ico" />
      <AvaloniaResource Include="Assets\favicon.ico" />
      <None Update="Cars\base.png">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </None>
      <None Update="Cars\CameraCar Base.png">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </None>
      <None Update="Cars\CameraCar Mask.png">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </None>
      <None Update="Cars\Cars.ini">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </None>
      <None Update="Cars\MX5 Cup.png">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </None>
      <None Remove="Assets\AD.png" />
      <AvaloniaResource Include="Assets\AD.png" />
    </ItemGroup>
</Project>
